export const invoiceData = [
  {
    id: "RT3080",
    createdAt: "2021-08-18",
    paymentDue: "2021-09-19",
    description: "Re-branding",
    paymentTerms: 30,
    clientName: "Jensen Huang",
    clientEmail: "jensenh@mail.com",
    status: "paid",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "106 Kendell Street",
      city: "SharBorough",
      postCode: "S1 0JY",
      country: "United Kingdom",
    },
    items: [{ name: "Brand Guidelines", quantity: 1, price: 1800.9 }],
    total: 1800.9,
  },
  {
    id: "XM9141",
    createdAt: "2021-08-18",
    paymentDue: "2021-10-20",
    description: "Graphic Design",
    paymentTerms: 30,
    clientName: "Alex Grim",
    clientEmail: "alexg@mail.com",
    status: "pending",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "84 Church Way",
      city: "Bradford",
      postCode: "BD1 9PB",
      country: "United Kingdom",
    },
    items: [
      { name: "Banner Design", quantity: 1, price: 156 },
      { name: "Email Design", quantity: 2, price: 200 },
    ],
    total: 556,
  },
  {
    id: "RG0314",
    createdAt: "2021-09-01",
    paymentDue: "2021-10-01",
    description: "Website Redesign",
    paymentTerms: 30,
    clientName: "John Morrison",
    clientEmail: "johnm@mail.com",
    status: "paid",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "47 Broadmead",
      city: "Bristol",
      postCode: "BS1 3DX",
      country: "United Kingdom",
    },
    items: [
      { name: "UI Design", quantity: 1, price: 6500 },
      { name: "Frontend Development", quantity: 1, price: 7500 },
      { name: "CMS Integration", quantity: 1, price: 2400 },
    ],
    total: 16400,
  },
  {
    id: "RT2080",
    createdAt: "2021-10-01",
    paymentDue: "2021-10-08",
    description: "Logo Design",
    paymentTerms: 7,
    clientName: "Alysa Warner",
    clientEmail: "alysaw@mail.com",
    status: "pending",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "22 Granville Road",
      city: "Leeds",
      postCode: "LS1 4BR",
      country: "United Kingdom",
    },
    items: [
      { name: "Logo Concept Drafts", quantity: 3, price: 120 },
      { name: "Final Logo Package", quantity: 1, price: 350 },
    ],
    total: 710,
  },
  {
    id: "AA1449",
    createdAt: "2021-10-15",
    paymentDue: "2021-10-16",
    description: "Social Media Kit",
    paymentTerms: 1,
    clientName: "Mellisa Clarke",
    clientEmail: "mellisac@mail.com",
    status: "pending",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "63 Fern Avenue",
      city: "Newcastle",
      postCode: "NE1 2BT",
      country: "United Kingdom",
    },
    items: [
      { name: "Instagram Templates", quantity: 10, price: 45 },
      { name: "Story Highlight Covers", quantity: 1, price: 180 },
      { name: "Content Strategy Doc", quantity: 1, price: 320 },
    ],
    total: 950,
  },
  {
    id: "TY9141",
    createdAt: "2021-10-24",
    paymentDue: "2021-11-24",
    description: "Mobile App UI",
    paymentTerms: 30,
    clientName: "Thomas Wayne",
    clientEmail: "thomasw@mail.com",
    status: "draft",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "8 Portman Square",
      city: "Manchester",
      postCode: "M1 2HG",
      country: "United Kingdom",
    },
    items: [
      { name: "Wireframes", quantity: 1, price: 1200 },
      { name: "High-Fidelity Screens", quantity: 12, price: 280 },
      { name: "Prototype & Handoff", quantity: 1, price: 800 },
    ],
    total: 5360,
  },
  {
    id: "FV2353",
    createdAt: "2021-11-05",
    paymentDue: "2021-11-12",
    description: "Print Collateral",
    paymentTerms: 7,
    clientName: "Anita Wainwright",
    clientEmail: "anitaw@mail.com",
    status: "draft",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "34 Albany Street",
      city: "Edinburgh",
      postCode: "EH1 3QB",
      country: "United Kingdom",
    },
    items: [
      { name: "Brochure Design", quantity: 2, price: 650 },
      { name: "Business Card Design", quantity: 1, price: 220 },
      { name: "Letterhead Design", quantity: 1, price: 180 },
    ],
    total: 1700,
  },
];
